/** @type {import('@types/eslint').Linter.Config} */
module.exports = {
  env: {
    node: true,
    commonjs: true,
    worker: true,
    jest: true,
    serviceworker: true,
    es6: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:promise/recommended',
    'plugin:typescript-sort-keys/recommended',
    'plugin:unicorn/recommended',
    'prettier',
  ],
  plugins: [
    '@typescript-eslint',
    'import',
    'simple-import-sort',
    'sort-destructure-keys',
    'sort-keys-fix',
    'typescript-sort-keys',
    'unused-imports',
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: { warnOnUnsupportedTypeScriptVersion: false },
  rules: {
    '@typescript-eslint/consistent-type-imports': 'error',
    'accessor-pairs': 'error',
    'block-scoped-var': 'error',
    'comma-dangle': ['error', 'always-multiline'],
    'default-case-last': 'error',
    'default-case': 'error',
    'default-param-last': 'error',
    'eqeqeq': 'error',
    'grouped-accessor-pairs': 'error',
    'import/first': 'error',
    'import/newline-after-import': 'error',
    'import/no-anonymous-default-export': 'error',
    'import/no-duplicates': 'error',
    'linebreak-style': ['error', 'unix'],
    'no-alert': 'error',
    'no-await-in-loop': 'error',
    'no-eq-null': 'error',
    'no-eval': 'error',
    'no-loss-of-precision': 'error',
    'no-template-curly-in-string': 'error',
    'no-trailing-spaces': 'error',
    'no-unneeded-ternary': 'error',
    'no-unused-vars': 'off',
    'no-use-before-define': 'error',
    'no-useless-concat': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-whitespace-before-property': 'error',
    'prefer-const': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'quote-props': ['error', 'consistent'],
    'quotes': ['error', 'single', { avoidEscape: true }],
    'require-await': 'error',
    'semi': ['error', 'never'],
    'simple-import-sort/exports': 'error',
    'simple-import-sort/imports': 'error',
    'sort-destructure-keys/sort-destructure-keys': 'error',
    'sort-keys-fix/sort-keys-fix': 'error',
    'sort-vars': 'error',
    'symbol-description': 'error',
    'unicorn/prefer-module': 'off',
    'unused-imports/no-unused-imports': 'error',
    'unused-imports/no-unused-vars': [
      'error',
      { vars: 'all', varsIgnorePattern: '^_', args: 'after-used', argsIgnorePattern: '^_' },
    ],
  },
}
